exclude: .*migrations\/.*
repos:
#  - repo: https://github.com/psf/black-pre-commit-mirror
#    rev: 24.4.2
#    hooks:
#        - id: black # haven't simple cote
#          exclude: \.py-tpl$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
        - id: check-yaml
        - id: end-of-file-fixer
        - id: trailing-whitespace
        - id: debug-statements
        - id: detect-private-key
        - id: check-merge-conflict
        - id: check-added-large-files
        - id: check-case-conflict
        - id: check-docstring-first
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
        - id: isort
          name: isort (python)
          exclude: "__init__"
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=120"]

#  - repo: https://github.com/pre-commit/mirrors-eslint
#    rev: v9.7.0
#    hooks:
#        - id: eslint  # from django repository
#  - repo: local
#    hooks:
#      - id: run-tests
#        name: Run Django tests
#        entry: bash -c "cd src/ && python manage.py test && cd .."
#        language: system
#        always_run: true
#        pass_filenames: false